server:
  port: 8010
#整合redis和mybatis
spring:
  redis:
    database: 1
    password:
    port: 6379
    host: localhost
  datasource:
    url: jdbc:mysql://localhost:3306/food?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.redis.entity

swagger:
  enable: true



